In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [ ]:
# Lendo o arquivo CSV e entendendo o conteúdo

df = pd.read_csv('data/pokemon_data.csv', encoding='latin-1')

df.head()

In [ ]:
# Verificando informações do DataFrame

df.info()

In [ ]:
# Verificando tamanho do DataFrame

df.shape

In [9]:
# Verificando colunas do DataFrame

df.columns

Index(['ID', 'Name', 'HP', 'Attack', 'Defense', 'Sp. Attack', 'Sp. Defense',
       'Speed', 'Base_Stats', 'normal_weakness', 'fire_weakness',
       'water_weakness', 'electric_weakness', 'grass_weakness', 'ice_weakness',
       'fighting_weakness', 'poison_weakness', 'ground_weakness',
       'flying_weakness', 'psychic_weakness', 'bug_weakness', 'rock_weakness',
       'ghost_weakness', 'dragon_weakness', 'dark_weakness', 'steel_weakness',
       'fairy_weakness', 'height_inches', 'height_meters', 'weight_pounds',
       'weight_kilograms', 'capturing_rate', 'gender_male_ratio', 'egg_steps',
       'egg_cycles', 'abilities', 'Type 1', 'Type 2', 'Classification_info',
       'Forms', 'gen', 'Is_Legendary', 'Is_Mythical', 'Is_Ultra_Beast',
       'number_immune', 'number_not_effective', 'number_normal',
       'number_super_effective'],
      dtype='str')

In [ ]:
# Descrevendo estatísticas do DataFrame

df.describe()

In [ ]:
# Verificando valores nulos no DataFrame

df.isnull().sum().sort_values(ascending=False)

In [ ]:
df["Type 2"].isna().sum() # Nem todo pokemon possui um segundo tipo, então é normal que haja valores nulos nessa coluna.

np.int64(499)

In [ ]:
# Verificando valores duplicados

df.duplicated().sum()

In [3]:
# Padronizando colunas

df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace(".", "")
)

In [4]:
df.columns

Index(['id', 'name', 'hp', 'attack', 'defense', 'sp_attack', 'sp_defense',
       'speed', 'base_stats', 'normal_weakness', 'fire_weakness',
       'water_weakness', 'electric_weakness', 'grass_weakness', 'ice_weakness',
       'fighting_weakness', 'poison_weakness', 'ground_weakness',
       'flying_weakness', 'psychic_weakness', 'bug_weakness', 'rock_weakness',
       'ghost_weakness', 'dragon_weakness', 'dark_weakness', 'steel_weakness',
       'fairy_weakness', 'height_inches', 'height_meters', 'weight_pounds',
       'weight_kilograms', 'capturing_rate', 'gender_male_ratio', 'egg_steps',
       'egg_cycles', 'abilities', 'type_1', 'type_2', 'classification_info',
       'forms', 'gen', 'is_legendary', 'is_mythical', 'is_ultra_beast',
       'number_immune', 'number_not_effective', 'number_normal',
       'number_super_effective'],
      dtype='str')

PRIMEIRAS ANALISES

In [ ]:
# Agrupando os Pokémons por Tipo 1 e calculando a média de ataque de cada tipo, ordenando do maior para o menor.

type1 = df.groupby('type_1')['attack'].mean().sort_values(ascending=False)

type1

In [ ]:
# verificando a média de cada estatística por tipo de Pokémon

type1 = df.groupby("type_1")[["hp", "attack", "defense", "sp_attack", "sp_defense", "speed"]].mean()
type1.sort_values("attack", ascending=False)

In [ ]:
bst = df.groupby("type_1")["base_stats"].mean().sort_values(ascending=False)

bst

In [ ]:
# Poder por geração

gen_power = df.groupby('gen')['base_stats'].mean().sort_values(ascending=False)

gen_power

In [ ]:
# Quantidade de Pokémons por geração

gen_count = df.groupby('gen').size()

gen_count

In [ ]:
# Poder x Captura

df["base_stats"].corr(df["capturing_rate"])

plt.scatter(df["capturing_rate"], df["base_stats"])

plt.xlabel("Taxa de Captura")
plt.ylabel("Poder Base")
plt.title("Relação entre Poder Base e Taxa de Captura")
plt.show()

In [ ]:
# Pokemons lendários x Não lendários - BST

df.groupby("is_legendary")["base_stats"].agg(['count', 'mean', 'median', 'min', 'max'])

              count        mean  median  min  max
is_legendary
0               961  416.253902   431.0  175  720
1                64  597.343750   580.0  200  690

In [13]:
# Pokemons lendários x Não lendários - Taxa de Captura

df.groupby("is_legendary")["capturing_rate"].agg(['count', 'mean', 'median', 'min', 'max'])

              count        mean  median  min  max
is_legendary
0               961  100.253902    65.0    3  255
1                64   15.906250     3.0    3  255

In [ ]:
# Pokemons lendários x Não lendários - Estatísticas

df.groupby("is_legendary")[
    ["hp", "attack", "defense",
     "sp_attack", "sp_defense", "speed",
     "base_stats"]
].mean()

,hp,attack,defense,sp_attack,sp_defense,speed,base_stats
is_legendary,,,,,,,
0,68.414152,75.806452,70.859521,67.929240,68.185224,65.255983,416.253902
1,96.765625,103.593750,97.562500,102.390625,100.859375,96.171875,597.343750

In [20]:
# Analise por tipos

type_analysis = (
    df.groupby("type_1")
    .agg(
        pokemon_count=("name", "count"),
        avg_hp=("hp", "mean"),
        avg_attack=("attack", "mean"),
        avg_defense=("defense", "mean"),
        avg_speed=("speed", "mean"),
        avg_bst=("base_stats", "mean")
    )
    .sort_values("avg_bst", ascending=False)
)

type_analysis

,pokemon_count,avg_hp,avg_attack,avg_defense,avg_speed,avg_bst
type_1,,,,,,
Dragon,37,79.594595,98.972973,75.216216,80.189189,490.162162
Steel,36,71.666667,88.000000,111.361111,57.222222,475.638889
Dark,45,75.800000,88.000000,71.622222,75.622222,454.733333
Psychic,60,71.783333,63.000000,67.183333,72.083333,447.050000
Fire,66,69.833333,82.606061,66.833333,74.106061,446.196970
Rock,58,68.310345,86.465517,98.103448,54.637931,441.155172
Fighting,40,76.075000,102.950000,72.350000,69.975000,437.075000
Fairy,29,71.379310,67.172414,70.965517,65.000000,436.413793
Ice,31,75.709677,74.419355,73.806452,61.612903,436.387097
Electric,59,64.779661,72.966102,62.101695,85.067797,436.305085
Flying,9,70.000000,79.888889,66.000000,83.000000,436.111111
Ground,40,74.475000,93.400000,85.900000,62.600000,434.575000
Ghost,35,61.800000,68.600000,75.485714,60.342857,431.171429
Poison,42,70.571429,75.547619,72.833333,70.380952,426.333333
Water,134,70.865672,72.343284,70.283582,66.261194,418.865672
Grass,103,65.766990,74.349515,70.893204,59.543689,413.116505
Normal,118,77.525424,74.381356,59.855932,67.983051,399.838983
Bug,83,56.493976,67.554217,69.578313,61.265060,374.638554

In [ ]:
# Equilibrio de atributos

stats = ["hp", "attack", "defense", "sp_attack", "sp_defense", "speed"]

df["stats_std"] = df[stats].std(axis=1)

df[["name","base_stats", "stats_std"]].sort_values("stats_std").head(10) # Quanto menor o stats_std, mais equilibrado é o Pokémon.

          name  base_stats   stats_std
797    Kartana         570   55.813977
410  Bastiodon         495   56.291207
712    Avalugg         514   58.946303
207    Steelix         510   59.413803
201  Wobbuffet         405   61.249490
798   Guzzlord         570   67.314189
804  Stakataka         570   69.902790
241    Blissey         540   93.273791
112    Chansey         450   93.327381
212    Shuckle         505  113.067089

In [26]:
df[["name","base_stats", "stats_std"]].sort_values("stats_std", ascending=False).head(10) # Quanto maior o stats_std, mais desequilibrado é o Pokémon.

          name  base_stats   stats_std
212    Shuckle         505  113.067089
112    Chansey         450   93.327381
241    Blissey         540   93.273791
804  Stakataka         570   69.902790
798   Guzzlord         570   67.314189
201  Wobbuffet         405   61.249490
207    Steelix         510   59.413803
712    Avalugg         514   58.946303
410  Bastiodon         495   56.291207
797    Kartana         570   55.813977